apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- pvc.yaml
- ingress.yaml

commonLabels:
  app: snn-fusion
  environment: production

namespace: snn-fusion
