apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snn-fusion-data-pvc
  namespace: snn-fusion
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
