global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "snn_fusion_rules.yml"

scrape_configs:
  - job_name: 'snn-fusion-api'
    static_configs:
      - targets: ['snn-fusion-api:8080']
    metrics_path: /metrics
    scrape_interval: 15s
    
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - snn-fusion
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
